### ISSUE TITLE
Wheres the download?

### ISSUE THREAD

**Issue by Zangoran** [TunkDesign/NeMa#14]
How much longer until the release? This looks really cool and a lot better than all the other web consoles I seen. Please get this out soon!

**Comment by TunkDesign** [comment]
That's a really good question, and I'll be glad to answer it!

While I can't give you a guaranteed date right now, I can tell you that we're not far away. We are currently in the process of going through everything and making sure everything works. And we're almost done with that.

After going through everything, we'll try to go public right away. Even if it is for a beta! We believe in NeManager!

I'll be sure to let you know when you can sign up! :)

I really hope this answered your question.

**Comment by Zangoran** [comment]
Thanks for the quick response! I will be looking forward to this! I was not expecting a quick response! Thanks!

**Comment by Zangoran** [comment]
@TunkDesign Do you think I would be able to be on the beta team when it comes out? Thanks!

**Comment by TunkDesign** [comment]
@Zangoran that shouldn't be a problem at all! I am pretty sure we'll have an open beta, but if we do a closed one, we will be sure to include you!

**Comment by Zangoran** [comment]
@TunkDesign Sorry for all the questions but, under the releases tab there are some downloads. Do those work? If so do I just follow the installation instructions? Thanks for your time!

**Comment by TunkDesign** [comment]
No worries at all. No, sorry, it does not work with only the executable you can find inside this repository. You will need to have access to a panel as well!

**Comment by Zangoran** [comment]
@TunkDesign Ok, so when it is released there will be steps on how to download and install everything together? Thanks for your time!

**Comment by TunkDesign** [comment]
@Zangoran, sorry for the slow reply! Yes, that's correct!

**Comment by Zangoran** [comment]
@TunkDesign Do you have a approximate release date? Like a certain month? This year? Thanks!

**Comment by TunkDesign** [comment]
@Zangoran, reaaally hard to say. I can't give you an exact date though. You fix one thing, and another thing breaks. There's a few things that needs to be fixed with the wrapper/daemon part of NeManager before we can go public. I want to say before the summer. I can't promise anything though, sorry :(

**Comment by Zangoran** [comment]
@TunkDesign Thanks! Its ok, take as long as you need. I just wanted a approximate date. And you gave me one. Thanks you for you time!

**Comment by Zangoran** [comment]
@TunkDesign How's it coming? Are you still predicting before summer? If not, how long do you think? Thanks for you time!

**Comment by TunkDesign** [comment]
@Zangoran Everything is going better than planned. Will probably be ready before summer now. Going to go though to see what needs to be done, this weekend!

**Comment by Zangoran** [comment]
@TunkDesign Great! Thanks for your replies!

**Comment by Zangoran** [comment]
@TunkDesign Summer is coming around. No rush, but I am just wondering of the status. Thanks for all your time!

**Comment by TunkDesign** [comment]
@Zangoran Sorry for the late response! The control panel is ready for a beta, we just need to fix the main website a bit, then we're good to go!

**Comment by Zangoran** [comment]
@TunkDesign Awesome! Would I be able to partake in the beta? Also will there be a tutorials not how to setup and use? Thanks again!

**Comment by TunkDesign** [comment]
@Zangoran Sure! We're going to make the beta open to everyone, so we can gather as much data as possible! There will be quite a few guides and tutorials to help you get started!

**Comment by Zangoran** [comment]
@TunkDesign Awesome! Do you have a release date of the beta? Or if you don't have a date set, could you message me when it is released? Thanks!

**Comment by TunkDesign** [comment]
@Zangoran I don't have a date as of yet, but I will make sure to let you know :)

**Comment by Zangoran** [comment]
@TunkDesign I saw the website, nemanager.com. I saw that the pro version will be free for beta. I was wondering if I partake in beta, if it will be free for me forever. Because my server doesn't have a steady income to afford $8 a month. Also is the beta coming soon?

**Comment by TunkDesign** [comment]
@Zangoran Sorry but the free pro version won't stay when the beta has ended. All accounts will get reset and people need to purchase a license. The $8 price tag isn't set in stone, and will change if people think it's too much. 

The beta should be coming before the end of this week. We have everything ready.

**Comment by Zangoran** [comment]
@TunkDesign Ok, Cool that the beta coming soon. I am thinking that $8 a
month is a little to much. I was thinking that you could

On Wednesday, June 1, 2016, Karl Håkansson <notifications@github.com> wrote:

> @Zangoran <https://github.com/Zangoran> Sorry but the free pro version
> won't stay when the beta has ended. All accounts will get reset and people
> need to purchase a license. The $8 price tag isn't set in stone, and will
> change if people think it's too much.
>
> The beta should be coming before the end of this week. We have everything
> ready.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/TunkDesign/NeMa/issues/14#issuecomment-223099086>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHURFQpwQmmEQCqoNZz87ELEW2D0YtVEks5qHd1fgaJpZM4HJLqq>
> .
>


-- 

*Zach Landquist *

   -CEO-

         of

  ZachMan Co.

ZachMan Co. is not a real business.

*E-mail: *zach@landquist.net

*Phone:* 262-290-3293

------------------------------------------------------------------------------

'Go and smell the roses.'- Anonymous

------------------------------------------------------------------------------



Landquist Family

**Comment by Zangoran** [comment]
@TunkDesign Ok, Cool that the beta coming soon. I am thinking that $8 a
month is a little to much. I was thinking that you could make it a yearly subscription for like $8 or something. How much is it costing to that you need to make a profit. I would make it so that you make a very small profit and then as you grow bigger raise the price slowly. That's just my opinion.

**Comment by TunkDesign** [comment]
@Zangoran The beta is now live. We will get a few instuctional videos up as soon as possible to help people get set up. In the meantime, hope you enjoy NeManager! If you need more help, please don't hesitate to ask in a new thread. Thanks :)

**Comment by Zangoran** [comment]
@tunkdesign Thanks so much!
