### ISSUE TITLE
Question about the server wrappper

### ISSUE THREAD

**Issue by Brandonv101** [TunkDesign/NeMa#15]
Hi there,

I would like to know if this would remove any of my existing files because I am currently using a .bat file to run the server. 

Thanks,
Brandon

**Comment by TunkDesign** [comment]
Hey @Brandonv101! NeManager doesn't remove any files unless you perform an action that is made to remove files, although these actions do have pop-ups letting you know what you're doing before actually doing them. You need to click twice to remove something.

That being said, you should always keep backups. NeManager can generate backups for you.
