### ISSUE TITLE
Could not connect to the wrapper. (111)

### ISSUE THREAD

**Issue by doublej93** [TunkDesign/NeMa#16]
I know this is due to my lack of Linux knowledge, but I followed the tutorial, everything is running fine, except I'm getting the error "Could not connect to the wrapper. (111)"

 I'm using an OVH VPS, just did a clean install of CentOS7.

I didn't set any special port so I assumed it as 20000. That didnt work. I looked in Netstat and I see this 
unix  2      [ ACC ]     STREAM     LISTENING     20107    /var/run/screen/S-root/1192.NeMa                                
It looks like its using 20107 then? and I'm still not able to connect either way if I send to either port. I'm a windows server admin by trade, so linux is still pretty foreign to me and I'm not sure what to look at next. Any direction would be appreciated. Thanks!

Josh

**Comment by TunkDesign** [comment]
Hey @doublej93! Let's see if we can solve this. 

It sounds like a firewall issue. The 111 error indicates that the connection was refused, but didn't time-out. We could contact your OVH VPS but we could not complete the request. 

As you didn't change the port, it should be 20000. Let's see if adding it to the firewall will solve your issue!

To open the port use the following command:
`firewall-cmd --permanent --zone=public --add-port=20000/tcp`
Then reload the firewall with:
`firewall-cmd --reload`

Let's hope that works!

**Comment by doublej93** [comment]
I get the following response.

[root@vps83712 ~]# firewall-cmd --permanent --zone=public --add-port=20000/tcp
-bash: firewall-cmd: command not found

For whatever reason when I install CentOS7 that feature is not there. Maybe removed by my VPS provider.

I did manually map it to port 80 (which I knew had to be open) and it worked! This at least lets me know I've got the setup right, but I might have to work with my VPS provider to get the port opened.

I guess my last question, is how do I stop the wrapper? I can CRTL-Z it, but that screws up the port being used.

**Comment by TunkDesign** [comment]
Yeah, it is probably better to contact OVH to see if they can solve the port issue. Glad it worked though!

NeManager was made to release the port if closed. You can force close NeManager with CTRL + C, and it should release the port.

**Comment by B3H1NDu** [comment]
Hey there, I am having the same problem as doublej93 except on Ubuntu. First I tried `firewall-cmd --permanent --zone=public --add-port=20000/tcp` to find it wasnt installed so I left it and did a quick google search, I then ran `sudo ufw enable` and `sudo ufw allow 20000` then `sudo ufw status` gave me positive results but I still got the error so then I ran `sudo apt install firewalld` and then `firewall-cmd --permanent --zone=public --add-port=20000/tcp` then `firewall-cmd --reload` but I still get the error. This is a very new install of ubuntu just for running servers. When I run `sudo iptables -L` this is what I get:

```
~$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
INPUT_direct  all  --  anywhere             anywhere
INPUT_ZONES_SOURCE  all  --  anywhere             anywhere
INPUT_ZONES  all  --  anywhere             anywhere
ACCEPT     icmp --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
FORWARD_direct  all  --  anywhere             anywhere
FORWARD_IN_ZONES_SOURCE  all  --  anywhere             anywhere
FORWARD_IN_ZONES  all  --  anywhere             anywhere
FORWARD_OUT_ZONES_SOURCE  all  --  anywhere             anywhere
FORWARD_OUT_ZONES  all  --  anywhere             anywhere
ACCEPT     icmp --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
OUTPUT_direct  all  --  anywhere             anywhere

Chain FORWARD_IN_ZONES (1 references)
target     prot opt source               destination
FWDI_public  all  --  anywhere             anywhere            [goto]
FWDI_public  all  --  anywhere             anywhere            [goto]

Chain FORWARD_IN_ZONES_SOURCE (1 references)
target     prot opt source               destination

Chain FORWARD_OUT_ZONES (1 references)
target     prot opt source               destination
FWDO_public  all  --  anywhere             anywhere            [goto]
FWDO_public  all  --  anywhere             anywhere            [goto]

Chain FORWARD_OUT_ZONES_SOURCE (1 references)
target     prot opt source               destination

Chain FORWARD_direct (1 references)
target     prot opt source               destination

Chain FWDI_public (2 references)
target     prot opt source               destination
FWDI_public_log  all  --  anywhere             anywhere
FWDI_public_deny  all  --  anywhere             anywhere
FWDI_public_allow  all  --  anywhere             anywhere

Chain FWDI_public_allow (1 references)
target     prot opt source               destination

Chain FWDI_public_deny (1 references)
target     prot opt source               destination

Chain FWDI_public_log (1 references)
target     prot opt source               destination

Chain FWDO_public (2 references)
target     prot opt source               destination
FWDO_public_log  all  --  anywhere             anywhere
FWDO_public_deny  all  --  anywhere             anywhere
FWDO_public_allow  all  --  anywhere             anywhere

Chain FWDO_public_allow (1 references)
target     prot opt source               destination

Chain FWDO_public_deny (1 references)
target     prot opt source               destination

Chain FWDO_public_log (1 references)
target     prot opt source               destination

Chain INPUT_ZONES (1 references)
target     prot opt source               destination
IN_public  all  --  anywhere             anywhere            [goto]
IN_public  all  --  anywhere             anywhere            [goto]

Chain INPUT_ZONES_SOURCE (1 references)
target     prot opt source               destination

Chain INPUT_direct (1 references)
target     prot opt source               destination

Chain IN_public (2 references)
target     prot opt source               destination
IN_public_log  all  --  anywhere             anywhere
IN_public_deny  all  --  anywhere             anywhere
IN_public_allow  all  --  anywhere             anywhere

Chain IN_public_allow (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh ctstate NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:20000 ctstate NEW

Chain IN_public_deny (1 references)
target     prot opt source               destination

Chain IN_public_log (1 references)
target     prot opt source               destination

Chain OUTPUT_direct (1 references)
target     prot opt source               destination
```
I hope this is enough for you to help me solve my problem :)
