### ISSUE TITLE
Could not connect to the wrapper. (110) (Windows 10)

### ISSUE THREAD

**Issue by DionisR3** [TunkDesign/NeMa#17]
I did everything true everything was default, i wrote my public ip to Host andd it isnt worked. It gives the error in title. I'm running windows 10.

**Comment by TunkDesign** [comment]
Hey @DionisR3! 

It seems that we timed out during the connection request to your computer. It sounds like it could possibly be your router blocking the port. Try opening the port and get back to me with the results 😃

After you've made sure it is open, try this website: http://www.canyouseeme.org

**Comment by TunkDesign** [comment]
I will take the silence as "it worked" and close this issue. If you still have issues, please reopen it.

**Comment by frigomanu** [comment]
The same hapends to me. I closed and reopen my server ports but nothing hapends, the error message keeps on appearing when I press "add"

**Comment by TunkDesign** [comment]
@frigomanu You need to open the NeManager ports as well! (20000 and 20021) Otherwise the website can't contact your computer. Hope that helps!

**Comment by frigomanu** [comment]
That helps a lot. You should write in the getting started page of the wiki (https://github.com/TunkDesign/NeMa/wiki/Getting-Started)
