### ISSUE TITLE
settings > system > logs missing menu options

### ISSUE THREAD

**Issue by daemonus** [TunkDesign/NeMa#18]
When viewing logs under settings menu links Accounts, Groups and About are missing from the left.
![bug](https://cloud.githubusercontent.com/assets/3434116/16032731/faa04266-325b-11e6-904a-6ed90e4043ea.png)

**Comment by TunkDesign** [comment]
This was actually an intended feature, believe it or not!

Although, we have now added the missing pages to the Logs page, as requested :)
