### ISSUE TITLE
When i started the wrapper it gave an error

### ISSUE THREAD

**Issue by melerpe** [TunkDesign/NeMa#21]
It gave this error

`Traceback (most recent call last):
  File "<string>", line 56, in <module>
  File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/scripts.filemanager", line 113, in start
AttributeError: type object '_socketobject' has no attribute 'SOL_SOCKET'

`

**Comment by melerpe** [comment]
More info:
First time use/installment

**Comment by TunkDesign** [comment]
This should now be resolved in the latest release (v2.1.2)! Sorry for the inconvenience!
