### ISSUE TITLE
Crash on server stop

### ISSUE THREAD

**Issue by melerpe** [TunkDesign/NeMa#22]
Hi,
Me with another bugreport
my wrapper begins to do crazy stuff after [23:57:18 INFO]: Saving chunks for level 'world_nether'/Nether
It does half respond
It is there. But it cannot start servers because idk

My acount email is melerpe.habbozz@live.nl

I dont know what is wrong!

**Comment by TunkDesign** [comment]
Hey @melerpe! Could you please paste the contents of the NeMa.log file?

**Comment by melerpe** [comment]
LOG: http://pastebin.com/ppfkueVq
I dont see any errors

**Comment by TunkDesign** [comment]
Sorry for the late reply!

Could you please try starting doing the same thing without any plugins enabled?

**Comment by melerpe** [comment]
I will make a second test server with 512mb ram

**Comment by TunkDesign** [comment]
I will take the silence as a "it worked", and close this issue. Please open this again if the error persists.
