### ISSUE TITLE
Cannot manage server

### ISSUE THREAD

**Issue by dedo1911** [TunkDesign/NeMa#24]
I've just press "reboot" then my server is stuck with this message:

Debug(Empty read; connection dead? Stream state: {"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false,"timed_out":false,"blocked":true,"eof":true})

Can't do anything.

**Comment by TunkDesign** [comment]
Could you please let me know if any errors has been logged, and if so, paste the log here? (NeMa.log)

**Comment by dedo1911** [comment]
No errors at all. Just the website bugged.

**Comment by daemonus** [comment]
I was getting a similar message in relation to [Issue#20](https://github.com/TunkDesign/NeMa/issues/20)

**Comment by TunkDesign** [comment]
The bridge between the panel and the wrapper has since been reworked. I am marking this as solved and closing it. If this is still an issue, please open again. Thanks :)
