### ISSUE TITLE
Website icons served over http on secure connection

### ISSUE THREAD

**Issue by daemonus** [TunkDesign/NeMa#25]
Don't know if this is the correct place but just noticed the icons on https://nemanager.com/ do not show up over SSL, I get firefox has blocked insecure elements.

**Comment by TunkDesign** [comment]
Seeing as we use the same server as the company website is on, for the NeManager website, https isn't a thing yet for it. What you're seeing when visiting the NeManager website through https, is the very outdated company website. We're going to move the NeManager website to its own server soon. As the Beta is free, we don't get any money to pay for everything, so we use what we already have. (Except for the panel, which is hosted on its own dedicated server).

I hope you understand! :)

**Comment by daemonus** [comment]
No worries :) flicked over to http after posting and saw the new one ;)
