### ISSUE TITLE
Can't add a wrapper

### ISSUE THREAD

**Issue by jpoulin** [TunkDesign/NeMa#27]
I'm getting a "too many redirects" error when I try to add a wrapper to my account.
<img width="613" alt="screen shot 2016-07-06 at 9 59 37 pm" src="https://cloud.githubusercontent.com/assets/2213372/16640361/59af9fca-43c5-11e6-8a49-60fa401b0088.png">

**Comment by TunkDesign** [comment]
Thank you for the report! It seems like I configured something wrong when I renewed the ssl certificate. It should work now :)
