### ISSUE TITLE
AWS Server - Ubuntu 14 - Issues launching wrapper - command not found

### ISSUE THREAD

**Issue by ToxicStar-Kevin** [TunkDesign/NeMa#28]
Gents,

Newbie question.  Apologies learning AWS, Linux and Minecraft all at once. I have Minecraft working but now want to manage it via the GUI hence I'm trying your application. I want to remote manage the Minecraft server in AWS (not a fan of line commands) but failing at the the first hurdle.
.
I assume I'm doing something stupid as I follow the clear instructions on the wiki for the server wrapper but when I try and run it I get command not found.   I assumed permissions and have tried variations and running under sudo without joy.

Help please.
![nema on aws](https://cloud.githubusercontent.com/assets/20357032/16689096/3e7ab8a2-4519-11e6-9a11-6227998ef9ab.PNG)

**Comment by B3H1NDu** [comment]
Follow the guide in the wiki.

Here: https://github.com/TunkDesign/NeMa/wiki/Getting-Started

**Comment by B3H1NDu** [comment]
Have you tried `sudo chown USER * -R`? In the SS you provided it seems to be the only thing you didn't do.

**Comment by ToxicStar-Kevin** [comment]
I had with Ubuntu substituted as I assumed the "USER" was the one i was assigned in.
I can give it another go tomorrow if you think that is the root cause but I did repeat the instructions a few times since they seemed straight forward enough

**Comment by TunkDesign** [comment]
This is really weird. You did change the NeMa file to an executable, so it should work.

Try running it with `/bin/bash ./NeMa`

**Comment by ToxicStar-Kevin** [comment]
Sorry there work and family getting in the way of my person hobbies.

Still no joy... at a lose as I can see the file and "less" it even though it is a binary.  Permissions and ownership seems correct it just doesn't run.

The underlining PocketMine PE is working fine.

any suggestion on what to look at?

ubuntu@ip-172-31-25-168:~$ /bin/bash ./NeMa
./NeMa: ./NeMa: cannot execute binary file
ubuntu@ip-172-31-25-168:~$ sudo /bin/bash ./NeMa
./NeMa: ./NeMa: cannot execute binary file
ubuntu@ip-172-31-25-168:~$


Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-74-generic x86_64)
Running PHP 7 and Java 8


ubuntu@ip-172-31-25-168:~$ wget https://nemanager.s3.amazonaws.com/wrapper/lin/NeMa
--2016-07-22 13:08:31--  https://nemanager.s3.amazonaws.com/wrapper/lin/NeMa
Resolving nemanager.s3.amazonaws.com (nemanager.s3.amazonaws.com)... 54.231.134.130
Connecting to nemanager.s3.amazonaws.com (nemanager.s3.amazonaws.com)|54.231.134.130|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7881806 (7.5M) [application/octet-stream]
Saving to: ‘NeMa’

100%[======================================>] 7,881,806   1.66MB/s   in 5.3s

2016-07-22 13:08:37 (1.42 MB/s) - ‘NeMa’ saved [7881806/7881806]

ubuntu@ip-172-31-25-168:~$ chmod +x NeMa
ubuntu@ip-172-31-25-168:~$ sudo chown ubuntu * -R
ubuntu@ip-172-31-25-168:~$ ./NeMa
-bash: ./NeMa: No such file or directory
ubuntu@ip-172-31-25-168:~$ ls
banned-ips.txt      NeMa                pocketmine.yml     start.sh
banned-players.txt  ops.txt             README.md          white-list.txt
bin                 players             server.log         worlds
CONTRIBUTING.md     plugins             server.properties
LICENSE             PocketMine-MP.phar  start_old.sh

ubuntu@ip-172-31-25-168:~$ ls -l NeMa
-rwxrwxr-x 1 ubuntu ubuntu 7881806 Jul 17 18:09 NeMa


ubuntu@ip-172-31-25-168:~$ ls -l
total 11696
-rw-rw-r-- 1 ubuntu ubuntu       0 Jul 22 13:10 ]
-rw-rw-r-- 1 ubuntu ubuntu       0 Jul 15 15:11 banned-ips.txt
-rw-rw-r-- 1 ubuntu ubuntu       0 Jul 15 15:11 banned-players.txt
drwxr-xr-x 3 ubuntu ubuntu    4096 Feb  7 20:59 bin
-rw-rw-r-- 1 ubuntu ubuntu    8349 Jul 15 08:05 CONTRIBUTING.md
-rw-rw-r-- 1 ubuntu ubuntu    7650 Jul 15 08:05 LICENSE
-rwxrwxr-x 1 ubuntu ubuntu 7881806 Jul 17 18:09 NeMa
-rw-rw-r-- 1 ubuntu ubuntu      14 Jul 15 08:08 ops.txt
drwxrwxr-x 2 ubuntu ubuntu    4096 Jul 15 16:51 players
drwxrwxr-x 4 ubuntu ubuntu    4096 Jul 15 11:54 plugins
-rw-rw-r-- 1 ubuntu ubuntu 3966174 Jul 15 08:05 PocketMine-MP.phar
-rw-rw-r-- 1 ubuntu ubuntu    5726 Jul 15 08:09 pocketmine.yml
-rw-rw-r-- 1 ubuntu ubuntu    2933 Jul 15 08:05 README.md
-rw-rw-r-- 1 ubuntu ubuntu   46638 Jul 16 10:36 server.log
-rw-rw-r-- 1 ubuntu ubuntu     482 Jul 15 15:11 server.properties
-rwxrwxr-x 1 ubuntu ubuntu    1156 Jul 15 14:34 start_old.sh
-rwxrwxr-x 1 ubuntu ubuntu    1383 Jul 15 15:01 start.sh
-rw-rw-r-- 1 ubuntu ubuntu      30 Jul 15 09:21 white-list.txt
drwxrwxr-x 3 ubuntu ubuntu    4096 Jul 15 08:09 worlds

ubuntu@ip-172-31-25-168:~$ sudo ./NeMa
sudo: unable to execute ./NeMa: No such file or directory
ubuntu@ip-172-31-25-168:~$ ./NeMa
-bash: ./NeMa: No such file or directory



ubuntu@ip-172-31-25-168:~$ sudo ./NeMa
sudo: unable to execute ./NeMa: No such file or directory
ubuntu@ip-172-31-25-168:~$ ./NeMa
-bash: ./NeMa: No such file or directory
ubuntu@ip-172-31-25-168:~$ sudo chmod +x NeMa
ubuntu@ip-172-31-25-168:~$ ./NeMa
-bash: ./NeMa: No such file or directory
ubuntu@ip-172-31-25-168:~$ less NeMa
"NeMa" may be a binary file.  See it anyway?
ubuntu@ip-172-31-25-168:~$

**Comment by TunkDesign** [comment]
Really weird. I need to try it for myself. I see that you're using Ubuntu 14.04.4, is that correct? Is it the desktop or server version?

**Comment by LordMantil** [comment]
Did you get this resolved? I'm having the same issue on ubuntu

**Comment by TunkDesign** [comment]
@LordMantil I need more information to do the testing! What Ubuntu version are you using (desktop or server)?

**Comment by LordMantil** [comment]
Hey, I thought I'd post my solution as I got it working.

You need to install the 32x libraries for Ubuntu if you are running 64x

sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 zlib1g:i386

**Comment by ToxicStar-Kevin** [comment]
Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-74-generic x86_64)
Running PHP 7 and Java 8

Ok I will give that a go as I'm running the default 64x from AWS images.

**Comment by ToxicStar-Kevin** [comment]
The addition of 32x libraries worked... I was able to connect to the wrapper... so i assume going forward the app can be tweaked to also work with 64x only ?

**Comment by TunkDesign** [comment]
@LordMantil thank you for the solution! I will make sure to add that to the Wiki page and credit you. I'll see if I can include those libraries somehow in upcoming builds.
