### ISSUE TITLE
Multiple Users Adding Wrapper?

### ISSUE THREAD

**Issue by smallkitten** [TunkDesign/NeMa#29]
I would just like to say that I really like what you are doing here with this program. It has really made managing my servers much easier. 

Really I have a question rather that a bug or problem: is it possible to have a wrapper running on a computer with its own specific key, and give friends with thair own accounts the key to the wrapper so that they can manage their own servers?

Sincerely,
        -Owen

**Comment by TunkDesign** [comment]
Thank you for those kind words!

So, to clarify, you're asking if it is possible to have user specific wrappers/servers?
That isn't possible per se, although you can achieve something like this with group permissions!
Create a server, create a permission group and set that group to only be able to access that server. After you've done that, assign a user to that group. You can have as many permission groups as you want.

Hope that answers your question :)

**Comment by smallkitten** [comment]
That sort of is it. :}

I was asking if I could just give the key of my wrapper to my friends with their own accounts so they can manage their servers.

I think what you said above would work but is that a pro thing?

Also, have you had any problems wth Pixelmon servers frequently crashing?

Thank you for the quick reply!
        -Owen

**Comment by smallkitten** [comment]
Also, I know on your site that you say that the price is subject to change if the community haggles you down. :} I don't want to haggle you down, but if you had an option to just pay a flat out price (I.E $30 or something once) I would totally pay for it. I can't really do monthly... :}

It's just a thought, I don't want to tell you how to run your company, and I sure you have your reasons for the monthly payment.

Thanks,
-Owen

**Comment by TunkDesign** [comment]
> I was asking if I could just give the key of my wrapper to my friends with their own accounts so they can manage their servers.

That isn't possible as of right now. I may look into it down the line, but as I said, you can achieve something like that, in the meantime :)

> I think what you said above would work but is that a pro thing?

It is a pro thing! However, you can get it for free during the beta period :D
See https://github.com/TunkDesign/NeMa/wiki/Open-Beta#more-features on how to upgrade your panel!

> Also, have you had any problems wth Pixelmon servers frequently crashing?

I haven't gotten any reports of it not working, but I haven't gotten any reports of it working either, so I can't help you there! It _should_ work just fine! (Don't quote me on that though)

> I don't want to haggle you down, but if you had an option to just pay a flat out price (I.E $30 or something once) I would totally pay for it. I can't really do monthly... :}

I have something in mind for that. NeManager was built as a hosted service, but as I plan to release a way for server hosts to use NeManager, I might as well do something for the users who can't do monthly payments.

I hope that clears some stuff up :)

**Comment by smallkitten** [comment]
Alright! Thanks for the reply!

That answers all of my questions at the moment. 

Just one more thing: when NeManager leaves beta will I get a notification? I just don't want to suddenly be charged every month, that's all. Or possibly make a payment! :}

Thanks for your patience and the straightforward reply!
-Owen

**Comment by TunkDesign** [comment]
You're not entering any real information when upgrading your panel, so so we can't charge you :)
But we will make sure to notify you before the beta ends :D

**Comment by smallkitten** [comment]
Ok, thanks!
-Owen

**Comment by smallkitten** [comment]
Ok, so I just tried to add a friend who made an account to the Accounts tab. However, it says: Sorry this email is already in use

Is he not supposed to have an account?

Thanks,
-Owen

**Comment by TunkDesign** [comment]
Aaah, he shouldn't have created an account of his own. Instead you're inviting him to your panel!
I need to clarify that somewhere.. I can remove his account from the system if you want?

**Comment by smallkitten** [comment]
Sure, do you need their email?

If so, here it is: eloymilan2003@gmail.com

Thanks for all of your help!
-Owen

**Comment by TunkDesign** [comment]
There you go :) He should be removed from the system!
Now just add him to your panel by visiting this link https://panel.nemanager.com/add/user

**Comment by smallkitten** [comment]
Alright! Everything is working perfectly!

Thanks again for all of your help!

I await the end of beta.
-Owen

**Comment by TunkDesign** [comment]
No worries Owen! Hope you enjoy using NeManager!

If you have any other questions/issues, let me know by submitting another issue :)
