### ISSUE TITLE
AWS Server - Ubuntu 14 - Failed to bind to port

### ISSUE THREAD

**Issue by ToxicStar-Kevin** [TunkDesign/NeMa#30]
**NeManager Wrapper - Version 2.1.3**

Trying to start the Minecraft server now I have got he wrapper working.

Once through the EULA flag change I ran into an issue with the port... I have confirmed the port is open etc in the AWS security group.
I have built a clean new Ubuntu 14.04 (added x32 libraries) and followed the wiki instructions.
I did stop and start the server but that did not help either.

![minecraft security group](https://cloud.githubusercontent.com/assets/20357032/17276285/c6b91910-571c-11e6-9761-5f928fd53716.JPG)

Starting wrapper..                       Wrapper loaded and accepting connections!
[DEBUG] http://panel.nemanager.com connected on port 59715

Starting Minecraft Server..           Failed to start server. Port already in use!

[11:36:54] [Server thread/INFO]: Starting minecraft server version 1.10.2
[11:36:54] [Server thread/INFO]: Loading properties
[11:36:54] [Server thread/INFO]: Default game type: SURVIVAL
[11:36:54] [Server thread/INFO]: Generating keypair
[11:36:54] [Server thread/INFO]: Starting Minecraft server on 52.42.183.49:25565
[11:36:54] [Server thread/INFO]: Using epoll channel type
[11:36:54] [Server thread/WARN]**: **** FAILED TO BIND TO PORT!**
[11:36:54] [Server thread/WARN]: The exception was: java.io.IOException: Error during bind(...): Cannot assign requested address
[11:36:54] [Server thread/WARN]: Perhaps a server is already running on that port?
[11:36:54] [Server thread/INFO]: Stopping server

**Comment by TunkDesign** [comment]
If you allow me, I will move your server into a temporary environment to do some debugging to find out why it is not binding the port.

**Comment by ToxicStar-Kevin** [comment]
No problem... still in the process of learning how it will work.
I have restarted the AWS server and used "screen -S" to keep the NeMa session going for you once I have logged out of putty.  I checked the behaviour is still the same and wrapper is working for you before replying.  
Feel free to do whatever you need. It is all vanilla at this point and simple to rebuild.

**Comment by TunkDesign** [comment]
Thank you! You will notice your wrapper disappearing from your panel. I will let you know when I move it back :)

**Comment by ToxicStar-Kevin** [comment]
No worry I will departing on my commute to work so so you should have a few days to play.  I will try and track the updates.

**Comment by TunkDesign** [comment]
Found the issue. The server could not bind to your public IP somehow, and therefore it wouldn't start. I changed it to use any interface and it worked (0.0.0.0). Will look into this further later.

**Comment by ToxicStar-Kevin** [comment]
Restarted the server and wrapper for you.  It is building the world as you promised.  If it is still trowing errors it must a symptom of the problem.
