### ISSUE TITLE
Enhancement - Deleting wrapper without the service being active.

### ISSUE THREAD

**Issue by ToxicStar-Kevin** [TunkDesign/NeMa#32]
Hi,

I could not delete the wrapper connection from the portal when the connected wrapper server was offline.
I started the server in AWS... it connected to wrapper and then I could delete the wrapper to move the service to a new server.

Not a defect precisely but I can see scenarios when the server has been "lost" and someone needs to delete the wrapper association. 

One for the thought pot and backlog list perhaps ?

Regards
Kevin

**Comment by TunkDesign** [comment]
This can now be achieved by enabling Two-Factor Authentication. After you've enabled TFA, you get the option to remove disconnected wrappers without having access to them. Thanks for the suggestion! :)
