### ISSUE TITLE
(Message) The wrapper this server is running on is out of date...

### ISSUE THREAD

**Issue by kennedyma** [TunkDesign/NeMa#34]
Getting the following message on my Dashboard:
 The wrapper this server is running on is out of date. Please consider updating it.

I just downloaded the software today.  Should I just ignore it?

**Comment by TunkDesign** [comment]
@kennedyma Have you tried restarting the wrapper?
This error message could be one of two things, but as you said you just downloaded NeManager, it can't be that you're using an out of date version. The other, most likely thing, is that something went wrong and you need to restart your wrapper. This error message could show up if the wrapper somehow failed to start completely.

Although that message shouldn't affect how the wrapper is running your servers, it should be restarted.

Hope this answered your question.
