### ISSUE TITLE
Connection lost no matter what

### ISSUE THREAD

**Issue by JakeNihilius** [TunkDesign/NeMa#35]
I keep getting the error:
 Connection lost!
Your connection to the server was lost. You are now forced to reload this page.
and a prompt to reload. This is my first time starting up, and i have no clue what is going on.

**Comment by TunkDesign** [comment]
Hey @JakeNihilius! Does this happen every time you try to access the server control panel?

**Comment by TunkDesign** [comment]
I am taking the silence as a confirmation that you no longer have this issue. Please reopen if you still have issues. Thank you.
