### ISSUE TITLE
Ip changed; cannot remove old wrapper

### ISSUE THREAD

**Issue by smallkitten** [TunkDesign/NeMa#36]
Hi, it's me again!

My public IP has changed so to some rewiring I did. Because of this, it is now saying that NeManager cannot connect to the wrapper. This is completely understandable, as that is has changed, but I cannot find a way to remove this old wrapper and continue on with this new one.

As well as this, I had set up a server on the new wrapper and got it started etc. Later in the day, however, when trying to access that server, it said the wrapper was offline. All other servers worked... Since then I have made a new server and moved all of the files there, but I am unable to delete this old corrupted one. Any suggestions?

Thanks,
-Owen

**Comment by TunkDesign** [comment]
The way of removing 'old' wrappers are currently broken. I will add that to the list of things to fix, that you gave me :)

I can remove it for you while we wait, just let me know the ID of the wrapper! (Click edit on the wrapper in question and look in the url for the ID)

**Comment by smallkitten** [comment]
Okay. Thanks for the quick reply, and the kind words! I really do hope
these posts are useful to you. I will try to let you know anything else I
see in the future.

I am unable to find where to click "edit" on the old wrapper; everywhere in
the "servers" tab it just says this: "This wrapper is currently offline!
Click here to reconnect!"

Am I missing something?

Thanks,
-Owen Schwartz

**Comment by TunkDesign** [comment]
This was fixed a while ago, but I forgot to update this issue. (https://github.com/TunkDesign/NeManager/commit/bbb0c54c1345b1a409e083e4cfc97ac4da1ebb5b)
