### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by smallkitten** [TunkDesign/NeMa#37]
I have been using NeManager for a little over a month now, and I have thrown some stuff at it. I wanted to write a quick report to let you guys know anything I have noticed. I apologize if you already were aware of some of these issues and this is just extra user stuff to sift through.

For the record, some of these things may be me being a moron, but hopefully not! (Please let me know if so!)
1. If a server crashes, and I try to restart it afterward, sometimes it will not boot, for it thinks that there is still an instance of a server running on that port. I'm not sure if this is something that you ar able to fix, or out of your hands. I have to reboot the wrapper to fix it.
2. The dashboard is extremely inconsistent. It will say servers are on that are not, and vice versa. 
3. Console says that all players have left, but the player's tab may sometimes show that players are still on the server.
4. The wrapper has locked me out on several occasions. It claims that the key is no longer valid. I have to reset it and update the wrapper in NeManager to fix it. 

```
**Debug(Connection to 'ws://200.213.143.923//' failed: Server sent invalid upgrade response: )
Authentication Failed
The wrapper key provided is not correct. Click here to update it.**
```
1. As I said in my other post, my is changed and there is no way to remove the old wrapper.
2. When logging in on different locations, sometimes I will get a "Failed to validate from the token" error that won't let me log  in. Also, the "Remember Me" option does not keep you logged in for that long. You have to log in often. I don't know if that is intentional.
3. When creating servers I will always get "`**Empty read; connection dead? Stream state: {"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false,"timed_out":false,"blocked":true,"eof":true}**`" when creating the server. I usaly have to reset the port peramiter and repeat untill it lets me make a server.
4. If I have trouble with one server and I decide that I want to delete it, frequently I am not able to. Even when there is a folder in the "servers" folder with the same name, it will return "`**No server with this ID exists.**`"
5. I will frequently have issues connecting to a running server. I can always go to the dashboard and click on the server, but a lot of the time it will bring up a "Connecting" screen and take a while to say that it cannot reach the wrapper, even tho the wrapper is running and I have perfect internet. The solution is usually to restart the wrapper or reload the page several times.

I hope at least one of these things was useful and can make this program even better! Thanks, guys!

-Owen Schwartz

**Comment by TunkDesign** [comment]
Thank you @smallkitten for the very detailed list of issues!
I will use it to my advantage and try to fix everything asap! 

You're certainly not a moron! :)

**Comment by TunkDesign** [comment]
Sorry for the late update, but I have now pushed an update to the panel which includes the following updates;

1. Changed internal process to be easier for forgotten password requests.
2. Fixed Two-Factor Authentication pin codes not syncing correctly with auth server.
3. Changed CSRF token error message to be more informative. Includes link to read more.
4. Possible fix for the server connection error 'Invalid upgrade response'.
5. Force Remove wrapper button now shown all the time for Superusers.
6. Fixed receipts being sent to the wrong user id.

I am working on the wrapper issues you're having. Currently working on the biggest, which is the playerlist. I hope to have everything fixed very soon. Can't give you any dates though.

**Comment by Simon-Schwartz** [comment]
Hello again!

Sorry about my late reply. To remove the wrapper I added two-factor authentication to my account. Now, however, I appear to be locked out of my account and the key that is generated on the google authenticator app on my phone is not working...

Any thoughts?

Thanks,
-Owen Schwartz

**Comment by TunkDesign** [comment]
Sorry for the, somewhat, late reply. 

That's really weird, I just tested turning Two-factor authentication on for my account, and there's no issues there. (Tried logging in as well)

Let me know if I should disable it for your account, so you can try again! :)

**Comment by Simon-Schwartz** [comment]
If you could disable it, that would be great! I'll try to set it up again.

I don't know what happened... Maybe I messed up the setup? I used the Google Authenticator app on my Andriod phone to scan the code. I had some trouble after that, as it kept generating new things to verify even after I put one of them in... On a restart of my phone, however, it started generating the codes for the login. These codes don't work, and this is where I am stuck now.

I apologize of all of my issues! You probably have better things to do than replying to me! I do appreciate your dedication to your community, it really makes the difference between "okay" software and "great" applications.

Thanks again,
-Owen Schwartz

**Comment by TunkDesign** [comment]
I have now disabled it :)

That's really weird. I've tried mutliple times on multiple devices and I've never had any issues. Hmm...

No worries, I don't have better things to do hahah! I try to be as active as possible, but with life getting in the way recently, I have not been able to be as active as I'd like. Still having a go at fixing all the issues you listed though :)

**Comment by Simon-Schwartz** [comment]
Success! I did the setup process again and I got it to work. 

The first time I tried logging in I got the same error (I did not copy it, sorry!) However, after waiting for another code to generate, it worked.

Thanks for your help,
-Owen Schwartz

P.S. I just realized that I have been posting on two different accounts. One is an account for my "server." Sorry if that was confusing!

**Comment by TunkDesign** [comment]
Awesome! Glad it worked! :D

That would have been confusing as heck, but you keep signing your name, so that definitely helped! :)

**Comment by TunkDesign** [comment]
Most, if not all of these issues has now been solved. Marking as solved and closing it! Thanks for the report :)
