### ISSUE TITLE
Cant make wrapper

### ISSUE THREAD

**Issue by Policeboy109** [TunkDesign/NeMa#38]
hey for some reason the wrapper wont create

Could not connect to the wrapper. (110)
I don't have a clue what is happening but ive tried it on 2 different ip's and still dosent work

**Comment by TunkDesign** [comment]
Hey @Policeboy109!

It seems that we timed out during the connection request to your computer. It sounds like it could possibly be your router blocking the port. Try opening the port and get back to me with the results 😃

After you've made sure it is open, try this website: http://www.canyouseeme.org

**Comment by Policeboy109** [comment]
still dont work

**Comment by TunkDesign** [comment]
I've just tested and made sure adding wrappers still works, and everything works just fine.

Are you sure you've opened the correct port? If you haven't changed any settings it should be port 20000.
http://www.canyouseeme.org should look like this if you've opened it correctly:
![Preview](http://i.imgur.com/98r0NCO.png)

**Comment by Policeboy109** [comment]
Hmm I tried it 3 times I'll try again

**Comment by Policeboy109** [comment]
ok finally got it working but it wont let me click start

**Comment by TunkDesign** [comment]
This should now be fixed. One of the required files appeared to be corrupted after an update. Sorry for this!
