### ISSUE TITLE
Unable to startup server

### ISSUE THREAD

**Issue by Kei-Shin** [TunkDesign/NeMa#39]
I created a wrapper and server like you normally would however when I went to the control panel and pressed the start button nothing happened. I've tried using a different jar file, creating a new server, and  creating a new wrapper, looking in the files it self for some signs  _(no eula is in the folder so I also tried making a copy of the eula text file and setting it to true and nothing changed)_ but I end up with a broken button and no error messages in the logs or on the website itself.

**Comment by TunkDesign** [comment]
This should now be fixed. One of the required files appeared to be corrupted after an update. Sorry for this!

**Comment by Kei-Shin** [comment]
Yep everything is fixed thanks!
