### ISSUE TITLE
Two-Factor Authentication Bug

### ISSUE THREAD

**Issue by Kei-Shin** [TunkDesign/NeMa#41]
I entered my email and password and clicked sign in afterwards im given the prompt to enter in my 6 digit code given by the app which I did but was told I am incorrect after double checking if I was incorrect which it seems im not. I don't know if this just user error or an actual bug but either way I am unable to log in.

**Comment by TunkDesign** [comment]
Hey @Kei-Shin, sorry for the late reply!

I have now disabled Two-Factor Authentication on your account, please try to enable it again. 
I will see if there's some syncing issues somewhere. It's a bit hard to test this, so it is good that you're reporting it.

If you still have this issue after the second try, please let me know!

**Comment by Kei-Shin** [comment]
I re enabled it and it gave me two NeManager tabs on the authentication app. The tabs give the same code each time but I figured it would be worth noting.

I also was able to log into my account now.

**Comment by TunkDesign** [comment]
This should no longer be an issue. Possible cause https://github.com/TunkDesign/NeManager/commit/059177100bbf37b3b67f82204baf2f3c9364b811
