### ISSUE TITLE
CPU usage wrong value

### ISSUE THREAD

**Issue by kevinvanberlo** [TunkDesign/NeMa#43]
The CPU usage keeps rising slowly till 100%, this value is different from the actual CPU usage.

**Comment by TunkDesign** [comment]
Sorry for the very late response!

What operating system did you run NeManager on? So I can do some testing!
Thanks :)

**Comment by Breadcrust** [comment]
Same issue, Windows 10 and Server 2016.

**Comment by TunkDesign** [comment]
This is fixed in the latest release. (3.0.0) 
(https://github.com/TunkDesign/NeManager-Wrapper/commit/fbb08e212887aaf7b26acf11d1ab08ecc19e4e26)
