### ISSUE TITLE
Paid for Professional, not given access to it

### ISSUE THREAD

**Issue by Sunlis** [TunkDesign/NeMa#44]
(I know this isn't a great place for account-related questions, but I also couldn't find a way to submit a ticket other than creating an Issue here)

I paid for NeManager on October 25 and got an email receipt, but can't access any of the pro features. I'm even getting ads at the top of each page. Is there someone I can email to rectify this?

**Comment by TunkDesign** [comment]
Sorry for the late reply, @Sunlis!

I have gone ahead and upgraded your panel. This is really weird, and I don't know why it is doing this. I need to look into it more. Could you please let me know the Fingerprint that was sent with the receipt? Thank you :)

**Comment by Sunlis** [comment]
evt_198YO4L6dJ4xQIPq2LnuycJ8
