### ISSUE TITLE
cannot type into command bar when server is loading, even if it needs confirmation

### ISSUE THREAD

**Issue by mookie1097** [TunkDesign/NeMa#45]
https://gyazo.com/c466da39e265c65e7c91818d9a71578f
this can be avoided with command line arguments, but should be changed.

**Comment by TunkDesign** [comment]
Thank you for reporting this!
I've never encountered something that requires response during startup before, so I didn't have that in mind when designing the console. Will definitely look into it!

**Comment by TunkDesign** [comment]
This was included a while back, so I am now marking this as solved. Thanks for the suggestion :)
