### ISSUE TITLE
Can't force stop server

### ISSUE THREAD

**Issue by Destarianon** [TunkDesign/NeMa#47]
Due to issues with Java selecting the wrong JVM i've had several servers fail to start. This made the dashboard completely unusable until I restarted the wrapper directly. The system does not realize that the server is not starting and leaves it in a starting state perpetually, and when I attempt to force stop the server (the only button that is clickable in that state) it loses connection and just restarts the dashboard to the exact same state.
![image](https://cloud.githubusercontent.com/assets/6621236/20645709/e1a28452-b42b-11e6-8358-2dc23918128b.png)

Edit: This occurs on ANY java based crash, including application exceptions or jvm errors.

**Comment by Destarianon** [comment]
A similar issue occurs because NeMa doesn't include libraries required to start a forge server, and it fails to start without those libraries. The wrapper becomes completely unresponsive and the dashboard doesn't even see it. 
![image](https://cloud.githubusercontent.com/assets/6621236/20645780/8b12b90c-b42d-11e6-9def-88a0a9418ae5.png)
Despite the wrapper not showing anything that seems like it's broken entirely.
![image](https://cloud.githubusercontent.com/assets/6621236/20645781/9d09dd98-b42d-11e6-8b59-92d520d8ef4d.png)
Restarting the wrapper fixes the issue, but is not an option in a production environment. It would also be nice if it included libraries required for forge, since it currently only imports a .jar

**Comment by TunkDesign** [comment]
Thank you for the very detailed bug report! I will put this on top of the TODO list, as it needs to be fixed as soon as possible. I'll take a look at it soon!

**Comment by TunkDesign** [comment]
The latest release of NeManager should fix these issues!
https://github.com/TunkDesign/NeMa/releases/tag/v2.2.0

If these still continues, please reopen!
