### ISSUE TITLE
BungeeCord Support

### ISSUE THREAD

**Issue by ZachTheDev** [TunkDesign/NeMa#48]
Love the wrapper! But I was wondering if you could add support for a BungeeCord server. Right now it does not work well with your wrapper. Thanks! If you need anymore info then just ask.

**Comment by TunkDesign** [comment]
We had it before, but had to disable it due to it being very unstable. Will look into adding it again! We definitely need it!

**Comment by Zangoran** [comment]
@TunkDesign Awesome! Thanks! Just let me know when you add it! Looking forward to it!
