### ISSUE TITLE
Two-Factor Authentication Not Working

### ISSUE THREAD

**Issue by Robospot** [TunkDesign/NeMa#50]
My account is under the email address robospot2000@gmail.com
After enabling two-factor authentication I have not been able to get into my account. I only enabled it to remove a test wrapper from the panel (which I was also not able to do). Could you please disable two-factor authentication on my account and remove the wrapper on my dashboard. Thanks.

**Comment by TunkDesign** [comment]
I'll have to check the syncing server again to make sure TFA works. 

I have now disabled TFA on your account and removed the test wrapper! Sorry for the inconvenience!

**Comment by Robospot** [comment]
Thanks
