### ISSUE TITLE
Panel being blocked

### ISSUE THREAD

**Issue by DaExoKay** [TunkDesign/NeMa#51]
Dead NeMa Team,

When I tried to add a self-built modpack and BungeeCord to NeMa, the wrapper-links became unusable. They simply claimed the wrapper did not exist (ports checked twice!). 

>{"stream_type":"tcp_socket/ssl","mode":"r+","unread_bytes":0,"seekable":false,"timed_out":false,"blocked":true,"eof":true})

When I added a new wrapper, and changed the port the issue was resolved. Now my panel is filled with two unused wrappers (including servers) which prevents me from proper configuration of my system. Could you please remove aforementioned wrappers from my system? If I try to do that myself, I receive a message:

> "To remove this wrapper, please enable Two-Factor Authentication."

I have already checked [issue 24](https://github.com/TunkDesign/NeMa/issues/24)

![ohne titel](https://cloud.githubusercontent.com/assets/2069785/22359985/2f665272-e44c-11e6-9f8e-857f72fc125e.jpeg)

Thank you!
Best regards

**Comment by TunkDesign** [comment]
I see you have successfully removed them! Good :)

In the future, just enable [Two-Factor Authentication](https://github.com/TunkDesign/NeMa/wiki/Rundown#two-factor-authentication) and you should be able to remove them :) (I am guessing you already did this hahah)
