### ISSUE TITLE
Jar File drop down empty

### ISSUE THREAD

**Issue by Breadcrust** [TunkDesign/NeMa#52]
I am running Windows 10 (Not server) and I have created a launchable ZIP using the instructions in the Wiki however the ZIP doesn't appear in the drop down. Help!

**Comment by TunkDesign** [comment]
Sorry for the confusion! 

This feature exists, but has not yet been released. The Wiki page was written in advance!
If you check the top of the Wiki page, you'll see this little message:

> _**As of NeManager 2.2.0 you have the ability to use zip files when creating a server. This will allow you to create servers that require more than just a single .jar to run.**_

This will be released soon! I just haven't had the time to release it! :(
Once again, sorry!

**Comment by TunkDesign** [comment]
This release has now been published! Have fun :)
https://github.com/TunkDesign/NeMa/releases/tag/v2.2.0
