### ISSUE TITLE
Restore from backup 

### ISSUE THREAD

**Issue by anders-brolien** [TunkDesign/NeMa#60]
Nothing happens when trying to restore from backup. I have three different backups for one world. Should restore be run when server is running? Where are the backups stored?

**Comment by TunkDesign** [comment]
Hey @anders-brolien! Have you checked the NeManager.log file for information on as to why nothing is happening? If there is an error in there, please let me know :)

If the server is running when restoring a backup, NeManager will turn the server off, before continuing restoring! 

The backup files should be located in a folder called "backups" in the NeManager root directory :)

Hope this answered your questions!

**Comment by anders-brolien** [comment]
Hej!
The NeMa.log was empty, where running a dockerized deployment. Unclear where the log files went. Changed that now.
However there we backups listed on the webpage, but none in the backup directory. 
Pressing restore did nothing. Luckily enough I was able recover the world by other means.
Thanks for a useful product!

/anders

**Comment by TunkDesign** [comment]
@anders-brolien weird! I've never tried to run NeMa inside docker before! It shouldn't make any difference however, which is weird. I'll make sure to run some tests inside Docker when I have time! :)

Tack för din felanmälan! Nu vet jag vad jag ska hålla utkik efter hahah :)
