### ISSUE TITLE
Website |  Captcha failure

### ISSUE THREAD

**Issue by 2019Z2** [TunkDesign/NeMa#64]
The captcha never loads (on ANY browser) / registration failure.
[https://1drv.ms/i/s!AivtrXwCPTROgTJQB_g7Gv4h4UBy?e=8dEZzL](url)
(OneDrive - read only, unlimited)

**Comment by TunkDesign** [comment]
Hey!

Thank you for bringing this to our attention! We've must have forgotten to install that function properly when updating. Really sorry for the inconvenience! This should be fixed now! :)
